### ISSUE TITLE
Dead link from plugin migration page

### ISSUE THREAD

**Issue by whitequark** [Vector35/sample_plugin#2]
The [instructions](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#what-about-my-old-plugin) you link to from issues like [this one](https://github.com/whitequark/binja_function_abi/issues/1) reference a file called `generate_plugininfo.py` in this repository. But there's no such file here.

**Comment by psifertex** [comment]
Sorry about that, I've updated the blog post with correct links. Just for completeness sake, the correct URL is: https://github.com/Vector35/community-plugins/blob/master/generate_plugininfo.py
